name: Deploy Plugin

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Check PHP Codes
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 8.2

  assets:
    name: Assets Test
    uses: tarosky/workflows/.github/workflows/npm.yml@main
    with:
      node_version: 22
      package: build

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [ lint, assets ]
    if: always()
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
